---
title: 'Baseline_all variables'
output: html_document
date: '2025-11-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)
require(readxl)
require(gmodels)
require(lsmeans)

'%ni%' <- Negate('%in%')
```

## R Markdown

```{r load data}
##read excel with all sheets, if needed
  
readxl_allsheet <- function(filename, tibble = FALSE) {
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    if(!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

survey <- readxl_allsheet("patient-survey.xlsx")

cre <- read_excel("60HN_ID_MALDITOF_confirmation_20251128.xlsx")
discharge_date <- read_excel("60HN - DischargeDate_no_discharge_sample_27Nov25.xlsx")

```


```{r cre carriage and species}
CRE_admission <- subset(cre, cre$SampleSchedule =='ADMISSION'); 
CRE_admission <- CRE_admission %>%
  filter(Identification_MALDITOF %ni% c('Aeromonas caviae', 'Aeromonas hydrophila','Aeromonas veronii', 'Enterococcus faecium'))

CRE_discharge <- subset(cre, cre$SampleSchedule =='DISCHARGE')
CRE_discharge <- CRE_discharge %>%
  filter(Identification_MALDITOF %ni% c('Acinetobacter baumannii', 'Aeromonas caviae',
                                        'Aeromonas hydrophila', 'Aeromonas veronii',
                                        "Cupriavidus gilardii", "Enterococcus faecium",
                                        "Pseudomonas putida"))

length(unique(CRE_admission$USUBJID)); length(unique(CRE_discharge$USUBJID))
## provincial hospitals 159, 010

## subset to specific CREC or CRKP
CREC_admission <- CRE_admission %>%
  filter(Identification_MALDITOF == "Escherichia coli") %>%
  select(USUBJID, SPEC_DATE)
CREC_admission <- CREC_admission[!duplicated(CREC_admission$USUBJID),]

CREC_discharge <- CRE_discharge %>%
  filter(Identification_MALDITOF == "Escherichia coli") %>%
  select(USUBJID, SPEC_DATE)
CREC_discharge <- CREC_discharge[!duplicated(CREC_discharge$USUBJID),]


CRKP_admission <- CRE_admission %>%
  filter(Identification_MALDITOF == "Klebsiella pneumoniae") %>%
  select(USUBJID, SPEC_DATE)
CRKP_admission <- CRKP_admission[!duplicated(CRKP_admission$USUBJID),]

CRKP_discharge <- CRE_discharge %>%
  filter(Identification_MALDITOF == "Klebsiella pneumoniae") %>%
  select(USUBJID, SPEC_DATE)
CRKP_discharge <- CRKP_discharge[!duplicated(CRKP_discharge$USUBJID),]

```

```{r Admission}
survey[["ADM"]] <- survey[["ADM"]] %>% filter(entry ==2) %>%
  mutate(hospitaltype = ifelse(SITEID %in% c('010','159'), 1, 2),
         age = 2025-YEAR_BIRTH +1,
         Ab_history = ifelse(ANB_ADMISSION %in% c(1,4),0,1),
         wardtype = ifelse(WARD_3==1, "surgical", "medical/ID"))

survey[["SCR"]] <- survey[["SCR"]]%>% filter(entry==2) %>%
  mutate(discharge_date = SPEC_DATE_DISCHARGE) 

discharge_date <-merge(discharge_date,survey[["SCR"]], by = 'USUBJID', all = T )

discharge_date <- discharge_date %>%
  mutate(DISCHARGE_DATE = ifelse(is.na(discharge_date), `Discharge date`,discharge_date)) %>%
  select(USUBJID, DISCHARGE_DATE)

admission <- merge(survey[["ADM"]],discharge_date, by = 'USUBJID', all = T )
admission <- admission %>%
  mutate(los = as.numeric((as.POSIXct(DISCHARGE_DATE) - as.POSIXct(ADMISSION_DATE))/86400+1))


# admission of CRE
#CREC
admission_CREC_admission <- merge(CREC_admission, admission, by = 'USUBJID', all = T)
admission_CREC_admission$CRE_admission <- ifelse(is.na(admission_CREC_admission$SPEC_DATE), 0, 1) #to identify those with CRE (here only CREC)


admission_CREC_discharge <- merge(CREC_discharge, admission, by = 'USUBJID', all = T)
admission_CREC_discharge$CRE_discharge <- ifelse(is.na(admission_CREC_discharge$SPEC_DATE), 0, 1)

#CRKP
admission_CRKP_admission <- merge(CRKP_admission, admission, by = 'USUBJID', all = T)
admission_CRKP_admission$CRE_admission <- ifelse(is.na(admission_CRKP_admission$SPEC_DATE), 0, 1)


admission_CRKP_discharge <- merge(CRKP_discharge, admission, by = 'USUBJID', all = T)
admission_CRKP_discharge$CRE_discharge <- ifelse(is.na(admission_CRKP_discharge$SPEC_DATE), 0, 1)


## get group mean and 95%CI, and difference test stats
test_dataset<- Admission_CRKP_discharge
anova_result <- aov(ONSET_DAYS~CRE_discharge, data=test_dataset); summary(anova_result)
lsmeans(anova_result, ~CRE_discharge); 
t.test(test_dataset$ONSET_DAYS); summary(subset(test_dataset, test_dataset$CRE_discharge==1)$ONSET_DAYS,nr.rm=T)


```



```{r Other datasets}
##General information
survey[["DEMO_HIS"]] <- survey[["DEMO_HIS"]] %>% filter(entry ==2) %>%
  mutate(JOB_final= case_when(JOB_SPECIFY %in% c("Cán bộ công chức", "Cán bộ xã") ~ 1,
            JOB_SPECIFY %in% c("Bảo vệ", "Cơ khí","Hộ lý", "Lái tàu thủy", "Lao động tự do","Vệ sỹ") ~ 4,
            JOB_SPECIFY %in% c("già", "Già","Hết độ tuổi lao động") ~ 8,
            JOB_SPECIFY %in% c("Ở nhà", "Tự do") ~ 9,
            .default = as.numeric(JOB)),
         householdsize = ADULT+CHILDREN,
         ALCOHOL_CUTDOWN_score = ifelse(ALCOHOL_CUTDOWN == 1, 0, 1),
         ALCOHOL_ANNOYED_score = ifelse(ALCOHOL_ANNOYED == 1, 0, 1),
         ALCOHOL_GUILTY_score = ifelse(ALCOHOL_GUILTY == 1, 0, 1),
         ALCOHOL_DRUG_score = ifelse(ALCOHOL_DRUG == 1, 0, 1),
         DRUG_CUTDOWN_score = ifelse(DRUG_CUTDOWN == 1, 0, 1),
         DRUG_ANNOYED_score = ifelse(DRUG_ANNOYED == 1, 0, 1),
         DRUG_GUILTY_score = ifelse(DRUG_GUILTY == 1, 0, 1),
         DRUG_DRUG_score = ifelse(DRUG_DRUG == 1, 0, 1),
         smoking = as.factor(ifelse(SMOKING == 1, "current smoker", ifelse(SMOKING == 2, "former smoker", "all non-smokers"))),
         children = as.factor(ifelse(CHILDREN == 0, "no children in the household", "with children in the household")),
         married = as.factor(ifelse(MARITAL ==1, "married", "other")),
         ambulatory = as.factor(ifelse(AMBULATORY == 1, "independent", "not independent"))
         )

survey[["DEMO_HIS"]] <- survey[["DEMO_HIS"]] %>% filter(entry ==2) %>%
  mutate(
    AlcoholCAGE = ALCOHOL_CUTDOWN_score+ALCOHOL_ANNOYED_score+ALCOHOL_GUILTY_score+ALCOHOL_DRUG_score, 
    DrugCAGE= DRUG_CUTDOWN_score+DRUG_ANNOYED_score+DRUG_GUILTY_score+DRUG_DRUG_score,
    job = as.factor(ifelse(JOB_final== 6, "farmer",ifelse(JOB_final== 7,"housewife",ifelse(JOB_final == 8, "retired", "all other jobs")))),
    )

survey[["DEMO_HIS"]] <- survey[["DEMO_HIS"]] %>% filter(entry ==2) %>%
  mutate(
    alcohol = as.factor(ifelse(AlcoholCAGE == 0, "0 problem", "1-4 problem")),
    drug = as.factor(ifelse(DrugCAGE == 0, "0 problem", "1-4 problem"))
  )

## Other history
InvasiveHistory <- survey[["DEMO_HIS_HISTORY_GRID"]] %>% filter(entry ==2) %>%
  filter(HIS_CONDITION ==1) %>%
  mutate(InvasiveHistory=ifelse(HIS_YN == 2, 'Yes', 'No'))
         
MedicationHistory <- survey[["DEMO_HIS_HISTORY_GRID"]] %>% filter(entry ==2) %>%
  filter(HIS_CONDITION ==2)%>%
  mutate(MedicationHistory=ifelse(HIS_YN == 2, 'Yes', 'No'))

TravelHistory <- survey[["DEMO_HIS_HISTORY_GRID"]] %>% filter(entry ==2) %>%
  filter(HIS_CONDITION ==3)%>%
  mutate(TravelHistory=ifelse(HIS_YN == 2, 'Yes', 'No'))

HealthcareHistory <- survey[["DEMO_HIS_HISTORY_GRID"]] %>% filter(entry ==2) %>%
  filter(HIS_CONDITION ==4)%>%
  mutate(HealthcareHistory=ifelse(HIS_YN == 2, 'Yes', 'No'))

#Discharge

discharge <- survey[["DIS"]] %>% filter(entry ==2) %>%
  mutate(
    ICDGroup = case_when(
    FINAL_DIAG_ICD10 %in% c('A04','A04.8','A04.9','A05.9','A06.4','A08.0', 'A08.5','A09','A09.0', 'A09.9')~'ID (Intestinal)',
    FINAL_DIAG_ICD10 %in% c('A15.0', 'A15.3', 'A16.2', 'A41', 'A41.5', 'A41.8', 'A41.9','A48','A49.9', 'A79.8','A79.9', 'A93', 'A94', 'A97','B00.1', 'B01','B01.2', 'B01.8', 'B02', 'B02.7', 'B02.8','B05', 'B05.2', 'B05.8', 'B05.9', 'B17', 'B18.1', 'B18.2', 'B34.9', 'B83.8') ~ 'ID (Other)',
    FINAL_DIAG_ICD10 %in% c('C18', 'C18.9; K56.6', 'C20','C22','C22.9', 'C34.9', 'C41', 'C61', 'C67.9', 'C70.0','C91.9', 'C92.2', 'C95.0', 'D12.0', 'D17', 'D21', 'D21.9', 'D23', 'D23.9', 'D27','D37.4', 'D38.1', 'D40.0', 'D44.0', 'D48.1')~'Neoplasms',
    FINAL_DIAG_ICD10 %in% c('I10', 'I10-E11-E25-I69', 'I10; H81', 'I11.9', 'I12.5', 'I18', 'I20', 'I20.0','I20.8','I21', 'I21.4', 'I21.9', 'I24.0', 'I25', 'I25.2', 'I25.5', 'I48', 'I48.0','I48.2','I50','I50.9','I61', 'I63','I63.8', 'I64','I67','I67-I10', 'I67 - I10','I69.4', 'I70.2', 'I80', 'I87.2','I88.8', 'I92.9', 'I95', 'I99') ~ 'Circulatory diseases',
    FINAL_DIAG_ICD10 %in% c('J01','J01.9','J02','J02.9','J04.0','J06','J06.9','J09', 'J10.1','J10.8','J11','J11.1','J11.8', 'J15', 'J15.9', 'J16', 'J17.1', 'J18', 'J18-I20.2', 'J18.0', 'J18.1', 'J18.8', 'J18.9', 'J20', 'J20.9', 'J40', 'J42', 'J44', 'J44.0', 'J44.1', 'J44.9', 'J45', 'J90','J96.0', 'J96.9','J96/18') ~ 'Respiratory diseases',
   FINAL_DIAG_ICD10 %in% c('K11.2','K12.3', 'K21', 'K21.0', 'K21.9', 'K22.6', 'K25', 'K25.0', 'K25.3', 'K25.9','K26.0', 'K27', 'K27-J20', 'K27.0', 'K27.3', 'K27.9', 'K29', 'K29.0', 'K29.1','K29.2','K29.6', 'K29.9','K30', 'K35', 'K35.1', 'K35.3','K35.5','K35.8', 'K35.9','K36', 'K40', 'K40.9', 'K42', 'K50', 'K52.3', 'K52.9', 'K56', 'K56.4', 'K56.6', 'K57.0', ' K57.3','K57.9','K58','K58.0', 'K59.1', 'K60.3', 'K61.0', 'K61.2', 'K62.1', 'K62.5', 'K63', 'K63.1','K63.5','K64', 'K64.2', 'K64.3', 'K64.8', 'K65', 'K71.2', 'K71.6', 'K72.0', 'K72.2', 'K73','K74', 'K74.0','K74.1','K74.2', 'K74.6', 'K75.8','K77','K78.6', 'K80', 'K80.0','K80.1','K80.2','K80.3','K80.4','K80.8', 'K81', 'K81.0','K83', 'K83.0','K85', 'K85.0', 'K85.8','K85.9', 'K86.1','K92','K92.2','K92.8','K92.9') ~ 'Digestive diseases',
   FINAL_DIAG_ICD10 %in%  c('N00','N13.2','N13.3','N13.6','N17','N17.9','N18','N18.4','N18.5','N18.9','N19','N20','N20.0','N20.1','N20.1, N23, N20.0, K21, M47','N20.2','N21.0', 'N21.1','N23','N28','N30.0', 'N30.8','N32.0', 'N34.1', 'N39.0', 'N40', 'N43.2','N45', 'N47','N48.1','N70') ~ 'Genitourinary diseases',
   TRUE ~ 'Other'),
   ICUduration = difftime(ICU_TO, ICU_FROM, units = 'days')+1,
   CVCduration = difftime(CVC_TO, CVC_FROM, units = 'days')+1,
   PVCduration = difftime(PVC_TO, PVC_FROM, units = 'days')+1,
   UCduration = difftime(UC_TO, UC_FROM, units = 'days')+1,
   IIDduration = difftime(IID_TO, IID_FROM, units = 'days')+1
   )


### patient ID 159-1-1-39 had CREC at admission, need to be admitted to ICU during hospital stay; continue to have CREC at discharge;
### patient ID 010-1-1-27 did not have CRKP at admission, need to be admitted to ICU during hospital stay; and acquired CRKP at discharge
```


```{r ANTIBIOTIC USE DURING HOSPITALIZATION}
# Antibiotic use during hospitalization at patient level
antibiotic_hospital <- survey[["ANT"]] %>% filter(entry ==2) %>%
  mutate(antibiotic_hospital = ifelse(ANB_HOS == 3, "yes", "no"))

#antibiotic agents used in hospital, each patient can have more than one antibiotic agents
antibiotic_hospital_agents <- survey[["ANT_ANB_HOSP_GRID"]] %>% filter(entry ==2) %>%
  mutate(agent = ifelse(ANB_OTHER_SPEC %in% c('Cefoperazol','Cefoperazole', 'Cefoperazon', 'Cefoperazone'), 'Cefoperazone',
                        ifelse(ANB_OTHER_SPEC %in% c('Senitram'), 'Ampicillin_sulbactam',
                               ifelse(ANB_OTHER_SPEC %in% c('Cefamandol','Cefemandol'), 'Cefamandol',
                                      ifelse(ANB_OTHER_SPEC %in% c('Vitabactam'), 'Cefoperazone_sulbactam',
                                             ifelse(ANB_OTHER_SPEC %in% c('Cefazolin'), 'Cefazolin',
                                             ifelse(ANB_OTHER_SPEC %in% c('Cefprozil'), 'Cefprozil',
                                                    ifelse(ANB_OTHER_SPEC %in% c('Cefradin'), 'Cefradin',
                                                           ifelse(ANB_OTHER_SPEC %in% c('Ceftizoxim', 'Ceftizoxime', 'Ceftizoxom', 'Ceftrizoxim'), 'Ceftizoxime',
                                                                  ifelse(ANB_OTHER_SPEC %in% c('Cefprozil'), 'Cefprozil',
                                                                  ifelse(ANB_OTHER_SPEC %in% c('Cefmetazol'), 'Cefmetazol', 
                                                                         ifelse(ANB_OTHER_SPEC %in% c('Ticarcillin + Acid clavulanic', 'Ticarcillin + Clavulanic', 'Ticarcillin/acid clavulanic'), 'Ticarcillin/acid clavulanic',
                                 ANB_HOSP_NAME))))))))))),
         number = 1,
         DOT = as.numeric((ANB_HOSP_END_DATE-ANB_HOSP_START_DATE)/86400 +1))



# calculate DOT of antibiotics used in hospital for each patient, at patient level
antibiotic_hospital_DOT <- antibiotic_hospital_agents %>%
  group_by(USUBJID) %>%
  summarise(number = sum(number), DOT=sum(DOT))

```

``` {r merge datasets}

#MERGE DATA to admission at patient level
all_data <- merge(admission, survey[["DEMO_HIS"]][,c("USUBJID","smoking","children","married","ambulatory","job","alcohol","drug")], by = "USUBJID", all=T )
all_data<- merge(all_data, InvasiveHistory[,c("USUBJID","InvasiveHistory")], by = "USUBJID", all=T )
all_data<- merge(all_data, MedicationHistory[,c("USUBJID","MedicationHistory")], by = "USUBJID", all=T )
all_data<- merge(all_data, TravelHistory[,c("USUBJID","TravelHistory")], by = "USUBJID", all=T )
all_data<- merge(all_data, HealthcareHistory[,c("USUBJID","HealthcareHistory")], by = "USUBJID", all=T )
all_data<- merge(all_data, discharge[,c("USUBJID","ICDGroup","ICUduration","CVCduration","PVCduration","UCduration", "IIDduration",
                                        "DISCHARGE","ICU","CVC","PVC","UC","IID")], by = "USUBJID", all=T )
all_data<- merge(all_data, antibiotic_hospital[, c("USUBJID","antibiotic_hospital")], by = "USUBJID", all=T )
all_data<- merge(all_data, antibiotic_hospital_DOT, by = "USUBJID", all=T )

# to add CRE data depending on type of carriage examined for further analysis
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
